var car = "civic";
var carCompany = "Suzuki";
var carColour = "Black";
var carModel = 2023;
var carType = "Automatic";
var bike = 150;
var bikeCompany = "Honda";
var bikeColour = "Red";
var bikeModel = 2023;
var bikeType = "new";
//For Car conditional test
console.log("\n\tFOR CAR TEST");
console.log("\nI think You have civci?");
console.log(car == "civic");
console.log("\nThe company of your car is Toyota?");
console.log(carCompany == "Toyota");
console.log("\nIs your car colour is White?");
console.log(carColour == "White");
console.log("\nI think your car model is 2023");
console.log(carModel == 2023);
console.log("\nYour car is definitely Automatic");
console.log(carType == "Automatic");
//For Bike conditional tests
console.log("\n\tFOR BIKE TEST");
console.log("\nYour bike is 70 right?");
console.log(bike == 70);
console.log("\nYour bike companny is Honda");
console.log(bikeCompany == "Honda");
console.log("\nThe colour of your bike is Black");
console.log(bikeColour == "Black");
console.log("\nI think your bike is of model 2024");
console.log(bikeModel == 2024);
console.log("\nYour bike is new I think");
console.log(bikeType == "new");
