"use strict";
let guests = ["Abdullah", "Amaan", "Minhal"];
console.log("\t\"PEOPLE INVITED AT MY DINNER\"");
console.log(guests[0]);
console.log(guests[1]);
console.log(guests[2]);
console.log("\t\"THE PEOPLE WHO CANT MAKE AT MY DINNER\" ");
console.log(guests[2]);
console.log(guests[1]);
console.log("");
console.log("\t\"NEW PEOPLE INVITED\" ");
guests[2] = "Ali";
guests[1] = "Taha";
console.log(guests[2]);
console.log(guests[1]);
